### ISSUE TITLE
event_id and timestamp pre-pended with "$__$$" on JSON export

### ISSUE THREAD

**Issue by rrbarbosa** [erik/mixport#6]
I exported events using basicaly the default conf. I changed only API credentials and output directory for the JSON section, commented everything else out. 

I then run `mixport` without any arguments. The events are exported correctly, as far as I can tell, however the `event_id` and the `timestamp` attributes are prepended with a `$__$$`. Not a show stopper, but triggers some extra-parsing from my side.

I looked through the source to try to patch it my self, but I have no idea where the string is being added.

Cool tool :+1:

**Comment by rrbarbosa** [comment]
I see now you did that on purpose. Closing the issue.

**Comment by erik** [comment]
Hmm, it might be worth looking into having a config option to specify the names of the event_id and timestamp keys for cases like this.

Thanks!
